version: '3.8'

services:
  mongodb:
    image: mongo:7-jammy
    container_name: censys-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=censys
      - MONGO_INITDB_ROOT_PASSWORD=censys_password
      - MONGO_INITDB_DATABASE=censys
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  app:
    build: .
    container_name: censys-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URL=mongodb://censys:censys_password@mongodb:27017/censys?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  mongodb_data:
